### ISSUE TITLE
Could you provide the pretrained model?

### ISSUE THREAD

**Issue by fengwhu** [RQuispeC/pytorch-ACSCP#1]
Thank you for sharing the code. But could you provide the pretrained model for this code?

**Comment by RQuispeC** [comment]
Hi, I have the trained models for ucf_cc_50 for its 5 folds, I can make them available if that's what you want

**Comment by RQuispeC** [comment]
trained models for UCF_CC_50 can be found in [here](http://www.liv.ic.unicamp.br/~quispe/crowd-counting/ACSCP_models/).

you should get

  | MAE | MSE
-- | -- | -- 
fold 1 | 531,64 | 880,12
fold 2 | 356,61 | 558,70
fold 3 | 134,40 | 154,99
fold 4 | 227,12 | 265,00
fold 5 | 158,87 | 219,02
AVERAGE | 281,73 | 415,56
