### ISSUE TITLE
Is the size of input images for training or testing fixed?

### ISSUE THREAD

**Issue by ghost** [RQuispeC/pytorch-ACSCP#4]
To maintain the original characteristics of the dataset, can we use the original size image as the model input?

**Comment by RQuispeC** [comment]
Short answer: Yes, we can use random size images for training and testing

Long answer:
The model has been designed to use 256x256 images, however, the code automatically will handle random size images for training and testing. 

For training, the data augmentation receives random size images and will augment creating 256x256 patches.

For testing, the code will automatically separate the image in 256x256 patches, applying padding when necessary, then feed them to the net. Finally, the 256x256 output patches are merged to create an output with the original input size.
