### ISSUE TITLE
results of other datasets

### ISSUE THREAD

**Issue by EillotY** [RQuispeC/pytorch-ACSCP#7]
use the original code in shanghai dataset part A has MAE:92 which is far from the author releases result.I dont know which part  cause problem .I set --people-thr 20 and also use the data_increating.So i want to know have you get a closer result of MAE:75 of shanghai_partA. 
Thank you very much!

**Comment by RQuispeC** [comment]
Hi @EillotY 
I didn't test this code for shanghai-tech, however I think that using --people-thr 20 for that dataset may create too few samples for training as shanghai-tech's images have less people amount that ucf-cc-50, for shanghai-tech (both part A and B) I would suggest to use --people-thr 0.
What's data_increating? didn't get that part
Hope you can replicate results for shanghai-tech

**Comment by EillotY** [comment]
ok ,i will try it.thanks a lot.
